@urldev = http://localhost:2001

### get all post
GET {{urldev}}/post
Content-Type: application/json

### get message broadcast
GET {{urldev}}/messages/broadCast
     ?idUserSend=1
     &idUserGet=4
Content-Type: application/json


### search user by username 
GET {{urldev}}/user/search
     ?query=2
Content-Type: application/json

### increment tym 
POST {{urldev}}/tym/increment
Content-Type: application/json

{
     "idUser": 1,
     "idPost": 50
}

###get all comment
GET {{urldev}}/comment
     ?idPost=50
Content-Type: application/json