@urldev = http://localhost:3000

### get all post
GET {{urldev}}/post
Content-Type: application/json

### get message broadcast
GET {{urldev}}/messages/broadCast
     ?idUserSend=1
     &idUserGet=4
Content-Type: application/json


### search user by username 
GET {{urldev}}/user/search
     ?query=2
Content-Type: application/json

### increment tym 
POST {{urldev}}/tym/increment
Content-Type: application/json

{
     "idUser": 1,
     "idPost": 50
}

###get all comment
GET {{urldev}}/comment
     ?idPost=50
Content-Type: application/json

###add comment
POST {{urldev}}/comment/add
Content-Type: application/json

{
     "idUser": 1,
     "idPost": 50,
     "content": "GOOD JOB!"
}

###deleteOne comment
POST {{urldev}}/comment/deleteOne
Content-Type: application/json

{
     "idComment": 1,
     "idPost": 50
}

###deleteOne comment

POST {{urldev}}/product/add
Content-Type: application/json

{
     "name": 1,
     "price": 50,
     "image": "images",
     "amount": 5,
     "category": "category",
     "size": "Size",
     "colors": "colors",
     "isOnline": 0
}